version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: app_db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker-compose/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panterest_clone_dev
      MYSQL_USER: user_panterest
      MYSQL_PASSWORD: panterest
    restart: always
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: app_phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    restart: always
    networks:
      - dev

  maildev:
    image: schickling/mailcatcher
    container_name: app_maildev
    ports:
      - "1080:1080"

  app:
    build: ./
    container_name: app
    ports:
      - "8000:80"
    volumes:
      - ./docker-compose/apache2_config:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  composer:
    image: library/composer:1.9.3
    container_name: app_composer
    volumes:
      - ./:/app
    depends_on:
      - app
    command: install


networks:
  dev:

volumes:
  db-data: